### PR TITLE
Setup flask

### PR DESCRIPTION
**Pull request by svenvanderburg**

### CODE REVIEW

**Comment by raar1** [comment]
Ahh, the annoying problem of ```rdflib``` not being up-to-date with python3.8 rears its ugly head again. (```AttributeError: module 'cgi' has no attribute 'escape'```). Let's just note for now that the visualization of the graph (with ```dot```) won't work past python3.7. I believe the ```rdflib``` people have fixed this now (it was quite a simple fix) but I don't know when the next release will be...

**Comment by raar1** [comment]
Note that ```graphviz``` should also be in ```requirements.txt```

**Comment by raar1** [comment]
Oh, and "Add a step by passing it's URI" should be "its" ;)

**Comment by svenvanderburg** [comment]
@raar1 I fixed the typo, added graphviz to requirements.txt, and added a dockerfile :) At least for running this demo your python3.8 problems are now history.

**Pull request merged**
