### PR TITLE
Add publication to nanopub

### PR DESCRIPTION
**Pull request by svenvanderburg**

### CODE REVIEW

**Review by raar1 — COMMENTED** [review]
Hmm, I got ```AttributeError: 'NoneType' object has no attribute 'get'``` when I clicked the publish button. That was caused by the line: ```nanopub_uri = publication_info.get('nanopub_uri')```

I added http://purl.org/np/RACLlhNijmCk4AX_2PuoBPHKfY1T6jieGaUPVFv-fWCAg#step as the first step, and http://purl.org/np/RA5D8NzM2OXPZAWNlADQ8hZdVu1k0HnmVmgl20apjhU8M#step as the second step.

Any idea what might be wrong?

**Comment by svenvanderburg** [comment]
_Hmm, I got ```AttributeError: 'NoneType' object has no attribute 'get'``` when I clicked the publish button. That was caused by the line: ```nanopub_uri = publication_info.get('nanopub_uri')```_
That is probably because you didn't install the latest `fairworkflows` library (in latest release publish_to_nanopub actually returns publication_info)

**Comment by raar1** [comment]
> _Hmm, I got `AttributeError: 'NoneType' object has no attribute 'get'` when I clicked the publish button. That was caused by the line: `nanopub_uri = publication_info.get('nanopub_uri')`_
> That is probably because you didn't install the latest `fairworkflows` library (in latest release publish_to_nanopub actually returns publication_info)

That's really odd - I pip uninstalled fairworkflows and it uninstalled v0.1.6, which was the only version installed according to ```pip```. Then I re-installed v0.1.6 and now it works... But in any case you were indeed right that it was somehow not using the new version.

**Comment by raar1** [comment]
OK, nice, the removal of localhost now makes the docker version work for me too.

**Pull request merged**
